### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [Uli12/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed good code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, make sure to comment the main parts of your code (both your HTML and CSS) in future projects. This will greatly help your development flow, especially as your projects get larger and more complex. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/29972053-c5a77a02-8ef8-11e7-997f-bbc1b369a4b7.png">

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/29972057-c6c0d42e-8ef8-11e7-9bfb-6017542dea6f.png">

Next off, rather than giving your brushes, frames and paint elements classes, you should instead assign them ID's since they are unique, individual elements. You usually use class when you want to give a group of elements the same styling. Here is a great resource that explains the difference between class and ID:

https://css-tricks.com/the-difference-between-id-and-class/

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by Uli12** [comment]
Thank you ad3429! 

Well noted on the ID vs Class issue. This was one of the concepts I was having trouble with (when to use which) so I will be sure to read up on the link you've provided. 
A few other concepts that are confusing are comments (as you can tell) and the use of the "nav" and "div" tag. What I am most confused about is, are the use of these concepts up to the discretion of the developer? 
For example initially I enclosed the whole brushes/frames/paint section in a 
"div" because I felt it was one big section. But then I didn't see a need for the element, so I removed the "div" tags. Would it be better practice to leave the "div" in case I need it later, or keep it out for the sake of keeping the coding minimal? Also while we are on the topic of "div", do I use this tag when I want to section off parts that have some similarities that I may need to use later in styling?

For comments, is there any structure around what I should comment on?
For example for this project, could I have put something like:
"!-- This section is for brushes--" or
"!-- Art supplies details start here ---" 
/* Use different background colors for each art supply */
Something like that? I wasn't sure what to write, so I didn't, but I understand now that it is good practice to comment as I go so when the code gets more complex myself (and other developers) can see what I was thinking at the time.

Lastly, my understanding of <nav> elements are that you use them to signal (or section off) an area of code that is all links or something that will navigate you elsewhere (whether on the same page or to a separate website or to another page on your website.) But I am super vague on this.

Also, one last question. (I promise) Is it better to place the "link" to link HTML and CSS right after the opening "heading" tag or closing "/heading" tag, or does it matter?

Thank you so much!
Yours,
Yurie

PS I used "" instead of angled brackets since the tags disappear from the thread when I use angled brackets.

**Comment by ad3429** [comment]
First off, it is considered good practice to wrap each section of your page in divs since this makes the code more clear and also re-usable in case you want to use that div again. So yes, it would be better to leave the div tag. 

To your second question, comments should be very short since you don't want them to distract from your main code. So the key is to write short, informative comments. For example, something like this would work fine:

<img width="210" alt="screen shot 2017-09-03 at 12 26 56 am" src="https://user-images.githubusercontent.com/25671399/30000550-9c60e308-903e-11e7-92bf-476aee62615e.png">

Regarding the links question, usually you want to put it right after the opening tag, but I've seen it been done at the bottom before as well. 

Thanks!

**Comment by Uli12** [comment]
Thank you so much! 
This has been hugely helpful :)

Yours,
Yurie
